#!/usr/bin/env bash
# Concatenates supabase/migrations/*.sql (in name order) into
# supabase/sql-editor/00_all_migrations.sql, the single file pasted into the
# Supabase dashboard SQL Editor. No Docker, no Supabase CLI.
#
# Usage: bash supabase/sql-editor/build.sh
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
migrations="$here/../migrations"
out="$here/00_all_migrations.sql"

shopt -s nullglob
files=("$migrations"/*.sql)
if [ ${#files[@]} -eq 0 ]; then
  echo "No migrations found in $migrations" >&2
  exit 1
fi

{
  echo "-- ============================================================================="
  echo "-- DSA — 00_all_migrations.sql"
  echo "-- GENERATED by supabase/sql-editor/build.sh. Do not edit by hand:"
  echo "-- edit supabase/migrations/*.sql and run the script again."
  echo "--"
  echo "-- Paste this whole file into Supabase → SQL Editor and click Run."
  echo "-- It is idempotent: running it again on the same project is safe."
  echo "--"
  echo "-- Contains:"
  for f in "${files[@]}"; do
    echo "--   $(basename "$f")"
  done
  echo "-- ============================================================================="
  for f in "${files[@]}"; do
    echo
    echo
    echo "-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    echo "-- >>> $(basename "$f")"
    echo "-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    echo
    cat "$f"
  done
} > "$out"

echo "Wrote $out (${#files[@]} migrations)"
