// French pronunciation lexicon for text-to-speech (GRAPH_SPECIFICATION §10).
//
// PLAIN DATA ONLY, so it can be edited by hand (and later by the admin).
// Book labels are printed in capitals without accents ("LIE A ADAM"); the
// screen keeps that spelling, and TTS speaks the form below.
//
// Keys: CAPITALS WITHOUT ACCENTS, words separated by single spaces.
// Values: the spoken/written form.
//   - lowercase value  → an ordinary word (it gets a capital only at the start of the question);
//   - Capitalised value → a proper noun or a book title (keeps its capital).
// A word that isn't listed: in capitals it is read as a name ("DAVID" → "David"),
// otherwise it is kept as written ("Le révolté").
// Numbers and ordinals ("TOME 1", "1ère", "2eme") are handled by rules, not here.

export interface PronunciationLexicon {
  /** Multi-word expressions, matched before single words (longest first). */
  phrases: Readonly<Record<string, string>>;
  words: Readonly<Record<string, string>>;
}

export const LEXICON_FR: PronunciationLexicon = {
  phrases: {
    'LIE A': 'lié à',
    'LIEE A': 'liée à',
    'LIES A': 'liés à',
    'ACTES DES APOTRES': 'Actes des Apôtres',
    'ANCIEN TESTAMENT': 'Ancien Testament',
    'NOUVEAU TESTAMENT': 'Nouveau Testament',
    'GRAND PRETRE': 'grand prêtre',
    'JE NE SAIS PAS': 'je ne sais pas',
    'PLUS CONNU': 'plus connu',
    'PLUS CONNUE': 'plus connue',
  },
  words: {
    // --- small words ---
    A: 'à',
    AU: 'au',
    AUX: 'aux',
    D: 'd',
    DE: 'de',
    DES: 'des',
    DU: 'du',
    EN: 'en',
    ET: 'et',
    L: 'l',
    LA: 'la',
    LE: 'le',
    LES: 'les',
    OU: 'ou',
    PAR: 'par',
    SA: 'sa',
    SES: 'ses',
    SON: 'son',
    SUR: 'sur',
    UN: 'un',
    UNE: 'une',
    DANS: 'dans',
    CONTRE: 'contre',
    AVEC: 'avec',
    PLUS: 'plus',
    MOINS: 'moins',

    // --- book structure ---
    ANCIEN: 'ancien',
    ANCIENS: 'anciens',
    ANCIENNE: 'ancienne',
    ANCIENNES: 'anciennes',
    NOUVEAU: 'nouveau',
    NOUVELLES: 'nouvelles',
    HOMME: 'homme',
    HOMMES: 'hommes',
    FEMME: 'femme',
    FEMMES: 'femmes',
    LIE: 'lié',
    LIEE: 'liée',
    LIES: 'liés',
    LIVRE: 'livre',
    LIVRES: 'livres',
    TOME: 'tome',
    CLASSE: 'classe',
    GROUPE: 'groupe',
    PERIODE: 'période',
    GENERATION: 'génération',
    GENERATIONS: 'générations',
    SECTION: 'section',
    AUTRES: 'autres',
    AUTRE: 'autre',
    CONNU: 'connu',
    CONNUS: 'connus',
    INCONNUS: 'inconnus',
    PREMIER: 'premier',
    PREMIERS: 'premiers',
    PREMIERE: 'première',
    PREMIERES: 'premières',
    DEUXIEME: 'deuxième',
    SECOND: 'second',
    TROISIEME: 'troisième',
    QUATRIEME: 'quatrième',
    CINQUIEME: 'cinquième',
    SIXIEME: 'sixième',
    SEPTIEME: 'septième',
    HUITIEME: 'huitième',
    NEUVIEME: 'neuvième',
    DIXIEME: 'dixième',
    DERNIER: 'dernier',
    DERNIERS: 'derniers',
    DERNIERE: 'dernière',
    DERNIERES: 'dernières',
    PENTATEUQUE: 'Pentateuque',
    EVANGILE: 'Évangile',
    EVANGILES: 'Évangiles',
    ACTES: 'Actes',
    APOTRE: 'apôtre',
    APOTRES: 'apôtres',
    EPITRE: 'épître',
    EPITRES: 'Épîtres',
    CHRONIQUES: 'Chroniques',
    ROIS: 'rois',
    ROI: 'roi',
    REINE: 'reine',
    JUGES: 'juges',
    PROPHETE: 'prophète',
    PROPHETES: 'prophètes',
    PROPHETIQUE: 'prophétique',
    PROPHETIQUES: 'prophétiques',
    POETIQUE: 'poétique',
    POETIQUES: 'poétiques',
    HISTORIQUE: 'historique',
    HISTORIQUES: 'historiques',
    ECRITURES: 'Écritures',
    TESTAMENT: 'Testament',
    PETITS: 'petits',
    GRANDS: 'grands',
    GRAND: 'grand',
    GRANDE: 'grande',

    // --- family and roles ---
    PERE: 'père',
    PERES: 'pères',
    MERE: 'mère',
    MERES: 'mères',
    FRERE: 'frère',
    FRERES: 'frères',
    SOEUR: 'sœur',
    SOEURS: 'sœurs',
    FILS: 'fils',
    FILLE: 'fille',
    FILLES: 'filles',
    ENFANTS: 'enfants',
    PARENTS: 'parents',
    FAMILLE: 'famille',
    PROCHES: 'proches',
    ONCLES: 'oncles',
    NEVEU: 'neveu',
    NEVEUX: 'neveux',
    DESCENDANTS: 'descendants',
    JUMEAUX: 'jumeaux',
    EPOUSE: 'épouse',
    EPOUSES: 'épouses',
    CONCUBINES: 'concubines',
    AINESSE: 'aînesse',
    ARRIERE: 'arrière',
    NE: 'né',
    NES: 'nés',
    NEE: 'née',
    NEES: 'nées',
    SERVITEUR: 'serviteur',
    SERVITEURS: 'serviteurs',
    DISCIPLES: 'disciples',
    COMPAGNONS: 'compagnons',
    AMIS: 'amis',
    ENNEMIS: 'ennemis',
    OPPOSANTS: 'opposants',
    CHEFS: 'chefs',
    PRINCES: 'princes',
    GUERRIERS: 'guerriers',
    VAILLANTS: 'vaillants',
    GARDIEN: 'gardien',
    GARDIENS: 'gardiens',
    PRETRE: 'prêtre',
    PRETRES: 'prêtres',
    SACRIFICATEUR: 'sacrificateur',
    SACRIFICATEURS: 'sacrificateurs',
    LEVITES: 'lévites',
    DIACRES: 'diacres',
    CHANTRES: 'chantres',
    EUNUQUES: 'eunuques',
    ESPIONS: 'espions',
    ENVOYES: 'envoyés',
    EMPLOYES: 'employés',
    OPPRIMES: 'opprimés',
    REVOLTE: 'révolté',
    REVOLTES: 'révoltés',
    AUTORITES: 'autorités',
    MECHANTS: 'méchants',
    DECHU: 'déchu',
    VERSE: 'versé',
    GENERAL: 'général',
    ETRANGER: 'étranger',
    ETRANGERS: 'étrangers',
    FIDELE: 'fidèle',
    FIDELES: 'fidèles',
    PAIENS: 'païens',
    PAIENNES: 'païennes',
    FAUX: 'faux',
    FOI: 'foi',
    PERDU: 'perdu',
    DROIT: 'droit',
    PROMESSE: 'promesse',
    GUERRE: 'guerre',
    SUPPLANTEUR: 'supplanteur',
    PRINCIPAUX: 'principaux',
    CHOISIS: 'choisis',
    SAGES: 'sages',
    BANDE: 'bande',
    REGNA: 'régna',
    TUA: 'tua',
    BONS: 'bons',
    INTENDANTS: 'intendants',
    GOUVERNEUR: 'gouverneur',
    ASSASSIN: 'assassin',
    ENSEIGNANTS: 'enseignants',
    PURIFICATEURS: 'purificateurs',
    DISTRIBUTEURS: 'distributeurs',
    LEADERS: 'leaders',
    FONCTIONNAIRES: 'fonctionnaires',
    TUTEUR: 'tuteur',
    ORGUEILLEUX: 'orgueilleux',
    SEUIL: 'seuil',
    TROUPES: 'troupes',
    PORTE: 'porte',
    NOMS: 'noms',
    OUVRIERS: 'ouvriers',
    JEUNE: 'jeune',
    PASTEUR: 'pasteur',
    BAPTISTE: 'Baptiste',
    SOUVERAIN: 'souverain',
    SOUVERRAIN: 'souverain',
    DEUX: 'deux',
    JE: 'je',
    OUI: 'oui',
    NON: 'non',

    // --- names and places whose accents matter for pronunciation ---
    DIEU: 'Dieu',
    JESUS: 'Jésus',
    MOISE: 'Moïse',
    ESAU: 'Ésaü',
    SAUL: 'Saül',
    ISRAEL: 'Israël',
    ISMAEL: 'Ismaël',
    NEHEMIE: 'Néhémie',
    NOE: 'Noé',
    CAIN: 'Caïn',
    JOSUE: 'Josué',
    OSEE: 'Osée',
    JEREMIE: 'Jérémie',
    ESAIE: 'Ésaïe',
    EZECHIEL: 'Ézéchiel',
    EZECHIAS: 'Ézéchias',
    ELIE: 'Élie',
    ELI: 'Éli',
    ELISEE: 'Élisée',
    ELYSEE: 'Élisée',
    ELEAZAR: 'Éléazar',
    ELIMELEC: 'Élimélec',
    ELISABETH: 'Élisabeth',
    EPHRAIM: 'Éphraïm',
    ETIENNE: 'Étienne',
    GEDEON: 'Gédéon',
    JEHU: 'Jéhu',
    JEPHTE: 'Jephté',
    JEROBOAM: 'Jéroboam',
    JEZABEL: 'Jézabel',
    JOEL: 'Joël',
    LEA: 'Léa',
    LEVI: 'Lévi',
    MANASSE: 'Manassé',
    MARDOCHEE: 'Mardochée',
    MICHEE: 'Michée',
    SIMEON: 'Siméon',
    REBECCA: 'Rébecca',
    DEBORAH: 'Débora',
    TIMOTHEE: 'Timothée',
    THIMOTHEE: 'Timothée',
    ZEBEDEE: 'Zébédée',
    BARNABE: 'Barnabé',
    BARTHELEMY: 'Barthélemy',
    ANDRE: 'André',
    HERODE: 'Hérode',
    HERODIAS: 'Hérodias',
    NICODEME: 'Nicodème',
    CAIPHE: 'Caïphe',
    SALOME: 'Salomé',
    BETHSABEE: 'Bethsabée',
    ISAI: 'Isaï',
    ABIGAIL: 'Abigaïl',
    AGEE: 'Aggée',
    SEDECIAS: 'Sédécias',
    PHILEMON: 'Philémon',
    ONESIME: 'Onésime',
    EPHESIENS: 'Éphésiens',
    HEBREUX: 'Hébreux',
    HEBRON: 'Hébron',
    JUDEE: 'Judée',
    EGYPTE: 'Égypte',
    JERICO: 'Jéricho',
    MESOPOTAMIE: 'Mésopotamie',
    AMOREENS: 'Amoréens',
    EDOMITES: 'Édomites',
    ROMAINS: 'Romains',
    ETERNEL: 'Éternel',
    MESSIE: 'Messie',
    ETHIOPIE: 'Éthiopie',
    EMMAUS: 'Emmaüs',
    ELIEZER: 'Éliézer',
    ELIHU: 'Élihu',
    ELIPHAZ: 'Éliphaz',
    ELIPHAZE: 'Éliphaz',
  },
};
